### GET test placeholder
GET http://localhost:8000/v1/

### GET /v1/channel/:id (success)
GET http://localhost:8000/v1/channel/1

### GET /v1/channel/:id (404)
GET http://localhost:8000/v1/channel/1000
